// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Intel and sold by Intel or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 17.0 (Build Build 602 07/19/2017)
// Created on Thu Jun 21 11:05:18 2018

LED7 LED7_inst
(
	.Q0(Q0_sig) ,	// input  Q0_sig
	.Q1(Q1_sig) ,	// input  Q1_sig
	.Q2(Q2_sig) ,	// input  Q2_sig
	.L0(L0_sig) 	// output [0:6] L0_sig
);

